image: docker

services:
  - docker:dind

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  script:
    - docker build --tag scheduler-core:latest ./scheduler_core
    - docker build --tag scheduler-telegram-bot:latest ./scheduler_telegram_bot