image: docker

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  script:
    - docker build --tag registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-core:latest --tag docker push registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-core:$CI_COMMIT_SHA ./scheduler_core
    - docker build --tag registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-telegram-bot:latest registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-telegram-bot:$CI_COMMIT_SHA ./scheduler_telegram_bot
    - docker push registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-core:latest
    - docker push registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-core:$CI_COMMIT_SHA
    - docker push registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-telegram-bot:latest
    - docker push registry.gitlab.com/ilichev-andrey/scheduler-service/scheduler-telegram-bot:$CI_COMMIT_SHA