image: docker

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:
  only:
    - master
  script:
    - docker pull $CI_REGISTRY_IMAGE/scheduler-core:latest
    - docker pull $CI_REGISTRY_IMAGE/scheduler-telegram-bot:latest
    - docker build --cache-from $CI_REGISTRY_IMAGE/scheduler-core:latest --tag $CI_REGISTRY_IMAGE/scheduler-core:latest --tag $CI_REGISTRY_IMAGE/scheduler-core:$CI_COMMIT_SHA ./scheduler_core
    - docker build --cache-from $CI_REGISTRY_IMAGE/scheduler-telegram-bot:latest --tag $CI_REGISTRY_IMAGE/scheduler-telegram-bot:latest --tag $CI_REGISTRY_IMAGE/scheduler-telegram-bot:$CI_COMMIT_SHA ./scheduler_telegram_bot
    - docker push $CI_REGISTRY_IMAGE/scheduler-core:latest
    - docker push $CI_REGISTRY_IMAGE/scheduler-core:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE/scheduler-telegram-bot:latest
    - docker push $CI_REGISTRY_IMAGE/scheduler-telegram-bot:$CI_COMMIT_SHA